name: CI

on: [push]

jobs:
  build:
    # This job runs on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Install gpg
        run: brew install gnupg
        
      - name: Switch XCode Version
        run: sudo xcode-select -s /Applications/Xcode_11.2.app
      - name: Install pod dependencies
        run: |
          cd ios
          pod install --verbose
        shell: bash
      - name: Build app
        run: |
          cd ios && xcodebuild archive \
            -workspace appname.xcworkspace \
            -scheme appname \
            -sdk iphoneos13.2 \
            -configuration Release \
            -archivePath $PWD/build/appname.xcarchive \
            IPHONEOS_DEPLOYMENT_TARGET=9.0
            PROVISIONING_PROFILE=${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }} \
            CODE_SIGN_IDENTITY="iPhone Distribution: Some Company (T343ff)"
      - name: Export app
        run: |
          cd ios && xcodebuild \
            -exportArchive \
            -archivePath $PWD/build/appname.xcarchive \
            -exportOptionsPlist $PWD/ci.plist \
            -exportPath $PWD/build
  #    - name: Releasing
  #      run: bundle exec fastlane release
  #      env:
  #        DEVELOPER_DIR: ${{ matrix.xcode }}
  #        YOUR_ENVIRONMENT_VARIABLES_HERE: ${{ "secret.XXX" }}

###### Android #####

#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v1
#    - name: set up JDK 1.8
#      uses: actions/setup-java@v1
#      with:
#        java-version: 1.8
#    - name: Main Build
#      run: bash ./gradlew :virocore:assembleRelease
#      working-directory: ./android
