name: CI

on: [push]

#jobs:
#  build:
#    runs-on: macos-latest
#    strategy:
#      matrix:
#        destination: ['platform=iOS Simulator,OS=13.1,name=iPhone 8']
#        xcode: ['/Applications/Xcode_11.1.app/Contents/Developer']
#    steps:
#     - name: Checkout
#       uses: actions/checkout@v1
#     - name: Bundle Install
#       run: bundle install
#       env:
#         BUNDLE_GITHUB__COM: x-access-token:${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
#     - name: Dependencies
#       run: |
#         carthage bootstrap --no-use-binaries --platform iOS --cache-builds
#         bundle exec pod install
#       env:
#         DEVELOPER_DIR: ${{ matrix.xcode }}
#     - name: Build and test
#       run: bundle exec fastlane scan --destination "${destination}" --scheme "YOUR_APP_SCHEME"
#       env:
#         destination: ${{ matrix.destination }}
#         DEVELOPER_DIR: ${{ matrix.xcode }}
###### IoS Without fastlane #####
jobs:
  build:
    # This job runs on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Install gpg
        run: brew install gnupg
        
      - name: Switch XCode Version
        run: sudo xcode-select -s /Applications/Xcode_11.2.app
      - name: Install pod dependencies
        run: |
          cd ios
          pod install --verbose
        shell: bash
      - name: Build app
        run: |
          cd ios && xcodebuild \
            -workspace ViroRenderer.xcworkspace \
            -scheme ViroKit \
            -sdk iphoneos13.2 \
            -configuration Release \
            IPHONEOS_DEPLOYMENT_TARGET=9.0 \
            CODE_SIGN_IDENTITY="iPhone Distribution: Some Company (T343ff)"
###### Android #####

#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v1
#    - name: set up JDK 1.8
#      uses: actions/setup-java@v1
#      with:
#        java-version: 1.8
#    - name: Main Build
#      run: bash ./gradlew :virocore:assembleRelease
#      working-directory: ./android
