name: RendererBuild
on: [push]

###### IoS Without fastlane ######
jobs:
  test-commit-to-bridge:
    runs-on: macos-latest
    steps:
      - name: Checkout Bridge
        uses: actions/checkout@master
        with:
          repository: dthian/viro
          ref: refs/heads/master

      - name: Update Bridge
        uses: actions/checkout@master
        with:
          repository: dthian/viro
          ref: refs/heads/master  
        
#          token: ${{ secrets.my_pat }}
#        
#  verifyCondition:
#    runs-on: ubuntu-latest
#    steps:
#      - name: print
#        run: echo verifyCondition testing...
#        if: "contains(github.event.head_commit.message, '[ViroReact]')"
#  ios_build:
#    # This job runs on macOS
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: Install gpg
#        run: brew install gnupg
#      - name: Set XCode Version 11.2
#        run: sudo xcode-select -s /Applications/Xcode_11.2.app
#      - name: Install pod dependencies
#        run: |
#          cd ios
#          pod install --verbose
#        shell: bash
#      - name: xcodebuild framework
#        run: |
#          cd ios && xcodebuild \
#            -workspace ViroRenderer.xcworkspace \
#            -scheme ViroKit \
#            -sdk iphoneos13.2 \
#            -configuration Release \
#            IPHONEOS_DEPLOYMENT_TARGET=9.0
            
###### Android #####            
#  android_build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v1
#    - name: set up JDK 1.8
#      uses: actions/setup-java@v1
#      with:
#        java-version: 1.8
#    - name: assmble release
#      run: bash ./gradlew :virocore:assembleRelease
#      working-directory: ./android
